### ISSUE TITLE
Config client with multiple repositories access

### ISSUE THREAD

**Issue by tvijayakannan** [adamkl/cloud-foundry-config-client#24]
I like to send application name dynamically instead of setting it in configuration . Is there any way to pass the application name,profile etc as config params to any function and it should send me the response and it's not necessary to keep them in static variable OR good to keep it in static memory and do refresh as per the interval configured. 

For example appName and environment defined in request path params and it will be send changed based on consumer need 
app.get("/branding/:appName/:environment", (req, res) => {
}

**Comment by adamkl** [comment]
I'm not quite sure I understand your use case.

The application configuration is already externalized to a Spring Config Server, so if you want to make changes to the configuration of a currently running application (maybe turning off a feature flag or something), you should just be able to make the change to the repo backing the Config Server and the `cloud-foundry-config-client` will pick up the change based on the refresh `interval`. 

If you are looking for a way to have different `appName` and `profile` for different deployed environments, you can set those values using environment variables and passing them into `cloud-foundry-config-client` through `process.env`.

**Comment by adamkl** [comment]
Wait, are you saying that you want to create a REST API proxy of sorts that uses `cloud-foundry-config-client` as a "data access layer" to the Spring Config Server?

Using this library as documented wouldn't be well suited for that use case because it uses a singleton to store the currently loaded config. Concurrent requests for different `appName`/`profile`/etc would lead to unpredictable results. 

If this *is* what you are looking to do, it should be possible with the existing exported methods `getLoaderConfig` and `loadAndRepeat` (which only repeats if an `interval` is specified). These are used internally by the static [`Config.load`](https://github.com/adamkl/cloud-foundry-config-client/blob/5fb9d512b5f4ad711373ca6e3252d50754850cce/src/cloudFoundryConfigClient.ts#L348) method to set the value of the singleton, but you should be able to use them directly to do what you want. 

You could probably do something like this:
```javascript
import { getLoaderConfig, loadAndRepeat } from 'cloud-foundry-config-client';

app.get("/branding/:appName/:profile", async (req, res) => {
  const { appName, profile } = req.params;
  const params = {
    appName,
    profile,
    configServerName: "myConfigServer",
    configLocation: "remote"
  };    
  const config = getLoaderConfig(params);
  await loadAndRepeat(config, params, loadedConfig => {
    res.json(loadedConfig);
  });
}
```
**Disclaimer** - I haven't tested the above code sample, but I think it should be close to working as is.

**Comment by tvijayakannan** [comment]
@adamkl Thanks for this code and i figure it out as well and did quick testing.Also profile is support comma separated value which is helping me to pull multiple values based on request parameters
